# Generated by Django 5.2.8 on 2026-02-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_medicine_last_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
