# Generated by ChatGPT — add pack field to Medicine model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_medicine_used_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='pack',
            field=models.CharField(max_length=100, blank=True, default=''),
        ),
    ]
