# Generated by Django 4.2.9 on 2026-06-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_add_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='place',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
