# Generated by Django 6.0.1 on 2026-09-19 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0005_medicine_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInventoryRiskPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField(auto_now_add=True)),
                ('current_stock', models.DecimalField(decimal_places=2, max_digits=12)),
                ('predicted_demand_30d', models.DecimalField(decimal_places=2, max_digits=12)),
                ('predicted_demand_60d', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('expected_excess_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('model_version', models.CharField(default='v1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_risk_predictions', to='inventory.medicine')),
            ],
            options={
                'indexes': [models.Index(fields=['medicine', 'prediction_date'], name='ai_inventor_medicin_587171_idx'), models.Index(fields=['risk_level'], name='ai_inventor_risk_le_f8742b_idx')],
            },
        ),
    ]
