# Generated by Django 5.2.8 on 2026-02-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='last_used',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
